// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpB5N6qkLDPKSp_FlpuSj3lkTXnUvWfE',
    appId: '1:152819163863:web:b9083c5b7ab98b1aa50692',
    messagingSenderId: '152819163863',
    projectId: 'instagram-a7218',
    authDomain: 'instagram-a7218.firebaseapp.com',
    storageBucket: 'instagram-a7218.appspot.com',
    measurementId: 'G-VBF8BX69HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg3tMXXoeSh06QHMsx9Zp9W8Nt-LSyt8Q',
    appId: '1:152819163863:android:0c1c726f472d0685a50692',
    messagingSenderId: '152819163863',
    projectId: 'instagram-a7218',
    storageBucket: 'instagram-a7218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq7wJyOH3IJC9HbO2FQ9e3w-p31oxt8bA',
    appId: '1:152819163863:ios:ccb4417d6e6253d3a50692',
    messagingSenderId: '152819163863',
    projectId: 'instagram-a7218',
    storageBucket: 'instagram-a7218.appspot.com',
    iosClientId: '152819163863-megdtj4hpi2qqifhtdmnk4cjvtr91p1q.apps.googleusercontent.com',
    iosBundleId: 'com.binx.bountier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq7wJyOH3IJC9HbO2FQ9e3w-p31oxt8bA',
    appId: '1:152819163863:ios:9c9cdaa5b61d0560a50692',
    messagingSenderId: '152819163863',
    projectId: 'instagram-a7218',
    storageBucket: 'instagram-a7218.appspot.com',
    iosClientId: '152819163863-71dr07lm9n2p5p9fb84fjbut9rc1vme1.apps.googleusercontent.com',
    iosBundleId: 'com.binx.bountier.RunnerTests',
  );
}
